"use client"

import { router } from "@/lib/router"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"

export default function RoutesDebugPage() {
  const routes = router.getRoutes()
  const urlPatterns = router.getUrlPatterns()

  const methodColors = {
    GET: "bg-green-100 text-green-800",
    POST: "bg-blue-100 text-blue-800",
    PUT: "bg-yellow-100 text-yellow-800",
    PATCH: "bg-orange-100 text-orange-800",
    DELETE: "bg-red-100 text-red-800",
  }

  return (
    <div className="min-h-screen bg-gray-50 p-8">
      <div className="max-w-6xl mx-auto">
        <Card className="mb-8">
          <CardHeader>
            <CardTitle>Django-style Router Debug</CardTitle>
            <CardDescription>All registered routes from the DefaultRouter</CardDescription>
          </CardHeader>
        </Card>

        <div className="grid gap-6">
          <Card>
            <CardHeader>
              <CardTitle>URL Patterns</CardTitle>
              <CardDescription>Unique URL patterns generated by the router</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="space-y-2">
                {urlPatterns.map((pattern, index) => (
                  <div key={index} className="font-mono text-sm bg-gray-100 p-2 rounded">
                    /api{pattern}
                  </div>
                ))}
              </div>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>All Routes</CardTitle>
              <CardDescription>Complete list of routes with methods and actions</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="space-y-4">
                {routes.map((route, index) => (
                  <div key={index} className="flex items-center justify-between p-4 border rounded-lg">
                    <div className="flex items-center gap-4">
                      <Badge className={methodColors[route.method as keyof typeof methodColors] || "bg-gray-100"}>
                        {route.method}
                      </Badge>
                      <code className="text-sm bg-gray-100 px-2 py-1 rounded">/api{route.pattern}</code>
                    </div>
                    <div className="flex items-center gap-2">
                      <span className="text-sm text-gray-600">Action:</span>
                      <Badge variant="outline">{route.action}</Badge>
                      <span className="text-sm text-gray-600">Name:</span>
                      <Badge variant="secondary">{route.name}</Badge>
                    </div>
                  </div>
                ))}
              </div>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  )
}
